services:
    modelbrouwers.authdjango.listener:
        class: modelbrouwers\mbstyles\event\listener
        arguments:
            - @template
            - @user
            - %core.php_ext%
        tags:
            - { name: event.listener }
