services:
    modelbrouwers.mbstyles.listener:
        class: modelbrouwers\mbstyles\event\listener
        arguments:
            - @config
            - @request
            - @template
            - @user
            - %core.php_ext%
        tags:
            - { name: event.listener }
    modelbrouwers.mbstyles.systemjs:
        class: modelbrouwers\mbstyles\command\systemjs
        arguments:
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: console.command }
